name: Docker Image CI

on:
  push:
    branches: 0.11.x

jobs:

  publish:

    runs-on: ubuntu-latest
    environment: DockerHub

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: snydergd
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: snydergd/askbot-devel:latest,snydergd/askbot-devel:0.11.x
